config/routes.rb
Rails.application.routes.draw do

  

resources :arcades do
    resources :games
  end

  resources :games, only: [:index, :show, :new, :create, :edit, :update]
  resources :players


  root 'static#home'
  get '/signup' => 'players#new'
  get '/signin' => 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :arcade
    belongs_to :player

    validates :name, :num_players, :cost, :working, :arcade_id, presence: true
    validates :name, uniqueness: true
    validates_inclusion_of :num_players, :in => 1..6
    
    def self.abc_order
        order(:name)
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def show
        if arcade_present?
            @arcade = Arcade.find(params[:arcade_id])
            @game = @arcade.games[params[:id].to_i]
            if @game != nil
                respond_to do |f|
                    f.js
                    f.html{render :show}
                    f.json {render json: @game}
                end
            else
                redirect_to arcade_path(@arcade)
            end
        else @game = Game.find_by(id: params[:id]) 
            if @game != nil
             @arcade = @game.arcade
                respond_to do |f|
                    f.js
                    f.html{render :show}
                    f.json {render json: @game}
                end
            else
                redirect_to root_path
            end
        end
    end


    def index
        if arcade_present?
            @arcade = Arcade.find(params[:arcade_id])
            @games = @arcade.games.abc_order
        else 
            @games = Game.abc_order
        end
        respond_to do |f|
            f.js
            f.html{render :index}
            f.json {render json: @games}
        end
    end

    def embedded_new
        security
        @game = Game.new
    end

    def new
        security
        @arcade = Arcade.find_by(id: params[:arcade_id])
        @game = Game.new
        respond_to do |f|
            f.js
            f.html{render :new}
            f.json {render json: @game}
        end
    end

    def create
        @game = Game.new(game_params)
        if @game.save
            respond_to do |f|
                f.js
                f.html{render :show}
                f.json {render json: @game}
            end
            @games = Game.abc_order
        else
            render 'new'
        end
    end

    def edit
        security
        @game = Game.find_by(id: params[:id])
        if  @game == nil
            redirect_to root_path
        end
    end

    def update
        @game = Game.find(params[:id])
        if @game.update(game_params)
            redirect_to @game
        else
            redirect to game_edit_path(@game)
        end
    end

    def destroy
        security
        @game = Game.find(params[:id])
        if authorized?
            @game.destroy
            redirect_to root_path
        else
            redirect_to game_path(@game)
        end
    end

    private

    def game_params
        params.require(:game).permit(:name, :num_players, :cost, :working, :arcade_id, :player_id)
    end

    def arcade_present?
        params[:arcade_id] && Arcade.find_by(id: params[:arcade_id]) != nil
    end

    def show_arcade
        if @arcade == nil
            @arcade = 1
        else
            @arcade.id
        end
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_errors.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@game.errors.count, "error") %>
      prohibited this game from being saved:
    </h2>
 
    <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/games/_form.html.erb
<div class="new-edit-form card">
  <%= form_with(model: game) do |f| %>
      <%= f.label 'Name of the game: ' %>
      <%= f.text_field :name %>
      <br>
      <%= f.label 'Maximum number of players: ' %>
      <%= f.number_field :num_players %>
      <br>
      <%= f.label 'How much will this game cost? ' %>
      <%= f.number_field :cost, :class => 'text_field', :step => 0.25 %>
      <br>
      <%= f.label 'This game will belong to which arcade?' %>
      <%= f.collection_select :arcade_id, Arcade.all, :id, :name, {:selected => show_arcade} %>
      <br>
      <%= f.label 'Is this game in working order?' %>
      <%= f.label 'No' %>
      <%= f.radio_button :working, false %>
      <%= f.label 'Yes' %>
      <%= f.radio_button :working, true %>
      <br>
      <%= f.hidden_field :player_id, :value => current_user.id %>
      <br>
      <%= f.submit %>
  <% end %>
</div>

app/views/games/_game.html.erb
<div class="container">
        <div class="card text-white bg-secondary mb-3 float-left inline" style="max-width: 18rem; height: 400px; width: 700px; margin: 30px;">
            <div class="card-header">
                <h4><%= game.name %><h4>
            </div>
            <div class="card-body">
                <p class="card-text">Max Players: <%= game.num_players %></p>
                <p class="card-text">Costs: <%= game.cost %> cents</p>
                <p class="card-text">In Order: <%= game.working %></p>
                <p class="card-text">Current Player: <%= game.player.username %></p>
                <br>
                <%= link_to 'Check this game out', game_path(game), id: 'game-show-route' %>
            </div>
        </div>
</div>

app/views/games/create.js.erb
$('#new-game-click form').remove();
$('#new-game-click a').show();
$('.new-edit-form.card').remove();
$('#game-holder').html("<%= j render @games.abc_order %>")
console.log("hello")

app/views/games/edit.html.erb
<div class="new-edit-form card">
  <h1 class="page-title">Edit The Game</h1>

<%= render 'errors' %>
<br>
<%= render 'form' %>
</div>

app/views/games/index.html.erb
<h1 class="page-headers">GAMES</h1>
<br>
<div class="row">
    <div class="col-6 new-path" id="new-game-click">
        <%= link_to "Create New Game", new_game_path, remote: true %>
        <br>
    </div>
</div>
<% if @arcade %>
    <div class="card mb-3" style="max-width: 900px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
            </div>
            <div class="card-body">
                <div class="col-md-8">
                    <%= render 'arcades/arcade' %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<div id="game-holder">
    <%= render partial: 'game', collection: @games %>
</div>

app/views/games/new.html.erb
<% if @arcade != nil %>
  <div class="card mb-3" style="max-width: 900px;">
      <div class="row no-gutters">
          <div class="col-md-4">
              <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
          </div>
          <div class="card-body">
              <div class="col-md-8">
                <%= render 'arcades/arcade' %>
              </div>
              <br>
              <%= link_to "Add A Game To Your Arcade", new_arcade_game_path(@arcade) %>
              <br>
              <br>
              <% if owner %>
                  <%= link_to "Edit Your Arcade", edit_arcade_path(@arcade) %>
                  <br><br>
                  <%= form_tag arcade_path(@arcade), method: "delete", data: { confirm: "Are you sure?" } do %>
                      <%= submit_tag "Close this Arcade" %>
                  <% end %>
              <% end %>
          </div>
      </div>
  </div>
<% end %>
  <h1 class="page-title">Add A New Game</h1>
  <%= render 'errors' %>
<br>
<%= render 'form' %>

app/views/games/new.js.erb
console.log('connected')
$('#new-game-click a').hide().parent().append("<%= j render 'form', game: @game %>")

app/views/games/show.html.erb
<div class="card mb-3" style="max-width: 900px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
        </div>
        <div class="card-body">
            <div class="col-md-8">
                <%= render 'arcades/arcade' %>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="card text-white bg-secondary mb-3 inline" style="max-width: 18rem; height: 400px; width: 700px; margin: auto; ">
        <div class="card-header">
            <h4><%= @game.name %><h4>
        </div>
        <div class="card-body">
            <p class="card-text">Max Players: <%= @game.num_players %></p>
            <p class="card-text">Costs: <%= @game.cost %> cents</p>
            <p class="card-text">In Order: <%= @game.working %></p>
            <p class="card-text">Current Player: <%= @game.player.username %></p>
            <br>
            <% if authorized? %>
                <%= link_to "Edit your game", edit_game_path(@game) %>
                <br><br>
                <%= form_tag game_path(@game.id), method: "delete", data: { confirm: "Pull the plug?" } do %>
                    <%= submit_tag "Shut down this game" %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>