config/routes.rb
Rails.application.routes.draw do

  

resources :arcades do
    resources :games
  end

  resources :games, only: [:index, :show, :new, :create, :edit, :update]
  resources :players


  root 'static#home'
  get '/signup' => 'players#new'
  get '/signin' => 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
    has_secure_password
    
    has_many :games
    has_many :arcades, through: :games

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, length: { minimum: 6}

    def self.from_omniauth(auth)
        where(uid: auth.uid).first_or_initialize.tap do |user|
          user.uid = auth.uid
          user.username = auth.info.name
          user.oauth_token = auth.credentials.token
          user.save!
        end
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    
    def show
        @player = Player.find_by(id: params[:id])
        if @player != nil
            render :show
        else
            redirect_to root_path
        end
    end
    
    def new
        @player = Player.new
    end

    def create
        @player = Player.new(player_params(:username, :age, :allowance, :password))
       
        if @player.save
            session[:player_id] = @player.id
            redirect_to @player
        else
            render 'new'
        end
    end

    def edit
        security
        @player = Player.find_by(id: params[:id])
    end

    def update
        @player = Player.find(params[:id])
        if @player.update(player_params(:username, :age, :allowance))
            redirect_to @player
        else
            redirect_to edit_player_path(@player)
        end
    end

    def destroy
        @player = Player.find(params[:id]).destroy
        if @player == current_user
            session.clear
        end
        redirect_to root_path
    end

    private

    def player_params(*args)
        params.require(:player).permit(*args)
    end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_errors.html.erb
<% if @player.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@player.errors.count, "error") %>
      prohibited this player from being saved:
    </h2>
 
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="new-edit-form card">
    <h1>Edit Your Stats </h1>

    <%= form_for @player do |f| %>
        <%= f.label 'Username' %>
        <%= f.text_field :username %>
        <br>
        <%= f.label 'Age' %>
        <%= f.number_field :age %>
        <br>
        <%= f.label 'Allowance' %>
        <%= f.number_field :allowance, :class => 'text_field', :step => 0.25 %>
        <br>
        <br>
        <%= f.submit %>
    <% end %>
</div>

app/views/players/new.html.erb
<div class="new-edit-form card">
  <h1 class="page-title">Create A New Player</h1>
  <%= render 'errors' %>

  <%= form_for @player, :html => {class: "form-group"} do |f| %>
    <%= f.label 'Create a Username: ' %>
    <%= f.text_field :username %>
    <br>
    <%= f.label 'How old are you? ' %>
    <%= f.number_field :age %>
    <br>
    <%= f.label 'What\'s your allowance? ' %>
    <%= f.number_field :allowance, :class => 'text_field', :step => 0.25 %>
    <br>
    <%= f.label 'Create a password: ' %>
    <%= f.password_field :password %>
    <br>
    <%= f.label 'Confirm password: ' %>
    <%= f.password_field :password_confirmation %>
    <br>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/players/show.html.erb
<div class="card mb-3" style="max-width: 900px;">
<div class="row no-gutters">
    <div class="col-md-4">
        <img src="https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
    </div>
    <div class="card-body">
        <div class="col-md-8">
            <h3><%= @player.username %></h3>
            <hr>
            <p>Age: <%= @player.age %></p>
            <p>Allowance: $<%= @player.allowance %></p>

            <% if current_user == @player %>
                <%= link_to "Adjust Your Stats", edit_player_path(@player) %>
                <br><br>
                <%= form_tag player_path(@player.id), method: "delete", data: { confirm: "Are you sure?" } do %>
                    <%= submit_tag "Take The Blue Pill" %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>