config/routes.rb
Rails.application.routes.draw do

  

resources :arcades do
    resources :games
  end

  resources :games, only: [:index, :show, :new, :create, :edit, :update]
  resources :players


  root 'static#home'
  get '/signup' => 'players#new'
  get '/signin' => 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arcade.rb
class Arcade < ApplicationRecord
    validates :name, :open_time, :close_time, :est_year, presence: true
    validates :name, uniqueness: true
    validates_inclusion_of :open_time, :close_time, :in => 1..12
    validates :est_year, :numericality => { greater_than_or_equal_to: 1970, less_than_or_equal_to: Time.now.year }

    has_many :games, :dependent => :delete_all
    has_many :players, through: :games

    def self.abc_order
        order(:name)
    end

    def self.highest_num_games
        joins(:games).group('arcades.id').order('count(games.arcade_id) DESC').first
    end
end

app/controllers/arcades_controller.rb
class ArcadesController < ApplicationController

    def index
        @arcades = Arcade.abc_order
        respond_to do |f|
            f.html{render :index}
            f.json {render json: @arcades}
        end
    end

    def show
        @arcade = Arcade.find_by(id: params[:id])
        no_arcade?
        @games = @arcade.games
        respond_to do |f|
            f.html{render :show}
            f.json {render json: @arcade}
        end
    end

    def new
        security
        @arcade = Arcade.new
    end

    def create
        @arcade = Arcade.new(arcade_params(:name, :location, :open_time, :close_time, :est_year, :owner_name))
        if @arcade.save
            redirect_to arcade_path(@arcade)
        else
            render 'new'
        end
    end

    def edit
        @arcade = Arcade.find_by(id: params[:id])
        not_owner?
    end

    def update
        @arcade = Arcade.find(params[:id])
        if @arcade.update(arcade_params(:name, :open_time, :close_time))
            redirect_to @arcade
        else
            redirect to arcade_edit_path(@arcade)
        end
    end

    def destroy
        security
        @arcade = Arcade.find(params[:id])
        if owner
            @arcade.destroy
            redirect_to arcades_path
        else
            redirect_to arcade_path(@arcade)
        end
    end

    private

    def arcade_params(*args)
        params.require(:arcade).permit(*args)
    end

    def no_arcade?
        if @arcade == nil
         redirect_to root_path
        end
    end

    def hours_of_operation
        "#{arcade.open_time} - #{arcade.close_time}"
    end

end

app/helpers/arcades_helper.rb
module ArcadesHelper
end

app/views/arcades/_arcade.html.erb
           
<h2 class="card-title"><%= @arcade.name %></h2>
<hr>
<p class="card-text">Located in: <%= @arcade.location %></p>
<p class="card-text">Owned by: <%= @arcade.owner_name %></p>
<p class="card-text">Open from: <%= "#{@arcade.open_time}am - #{@arcade.close_time}pm" %></p>
<p class="card-text">Open since: <%= @arcade.est_year %>
<br>
<br>
<%= link_to 'Go to Arcade', arcade_path(@arcade) %>

app/views/arcades/_arcades.html.erb
<% @arcades.each do |arcade| %>
    <div class="card mb-3" style="max-width: 900px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
            </div>
            <div class="card-body">
                <div class="col-md-8">            
                    <h2 class="card-title"><%= arcade.name %></h2>
                    <hr>
                    <p class="card-text">Located in: <%= arcade.location %></p>
                    <p class="card-text">Owned by: <%= arcade.owner_name %></p>
                    <p class="card-text">Open from: <%= "#{arcade.open_time}am - #{arcade.close_time}pm" %></p>
                    <p class="card-text">Open since: <%= arcade.est_year %>
                    <br>
                    <br>
                    <%= link_to 'See This Arcades Games', arcade_games_path(arcade) %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/arcades/_errors.html.erb
<% if @arcade.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@arcade.errors.count, "error") %> 
    prohibited this arcade from being saved:</h2>

    <ul>
      <% @arcade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/arcades/_form.html.erb
<%= form_for(@arcade) do |f| %>
    <br>
    <%= f.label 'Name of arcade: ' %>
    <%= f.text_field :name %>
    <br>
    <%= f.label 'Where is the arcade located? ' %>
    <%= f.text_field :location %>
    <br>
    <%= f.label 'At what time will your arcade open: ' %>
    <%= f.number_field :open_time %>
    <br>
    <%= f.label 'At what time will your arcade close: ' %>
    <%= f.number_field :close_time %>
    <br>
    <%= f.label 'What year was the acrade established? ' %>
    <%= f.number_field :est_year %>
    <br>
    <%= f.hidden_field :owner_name, :value => current_user.username %>
    <br>
    <%= f.submit %>
<% end %>

app/views/arcades/edit.html.erb
<div class="new-edit-form card">
    <h2>Update Your Arcade Information</h2>
    <%= render 'errors' %>
    <br>
    <%= render 'form' %>
</div>

app/views/arcades/index.html.erb
<h1 class="page-headers">ARCADES</h1>
<div class="container">
    <% @arcades.each do |arcade| %>
        <div class="card text-white bg-secondary mb-4 float-left inline" style="max-width: 21rem; width: 1000px; margin: 5px;">
                <button class="btn btn-primary arcade-id-<%= arcade.id %>" id="arcade-name-<%= arcade.id %>" type="submit"><%= arcade.name %></button>
        </div>
    <% end %>
</div>
<div class="container" style="margin-top: 300px">
    <div id="arcade-show">
    </div>
</div>
<div class="container" style="margin-top: 100px">
        <div id="games-show">
        </div>
    </div>
</div>
<script>clickSpecific()</script>

app/views/arcades/most.html.erb
<div class="card mb-3" style="max-width: 900px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
        </div>
        <div class="card-body">
            <div class="col-md-8">
                <%= render 'arcade' %>
            </div>
        </div>
    </div>
</div>

app/views/arcades/new.html.erb
<div class="new-edit-form card">

  <h2>Register Your Arcade</h2>

  <%= render 'errors' %>
  <br>
  <%= render 'form' %>
</div>

app/views/arcades/show.html.erb
<div class="card mb-3" style="max-width: 900px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" class="card-img" alt="...">
        </div>
        <div class="card-body">
            <div class="col-md-8">
                <%= render 'arcade' %>
            </div>
            <%= link_to "Add A Game To Your Arcade", new_arcade_game_path(@arcade) %>
            <br>
            <% if owner %>
                <%= link_to "Edit Your Arcade", edit_arcade_path(@arcade) %>
                <br><br>
                <%= form_tag arcade_path(@arcade), method: "delete", data: { confirm: "Are you sure?" } do %>
                    <%= submit_tag "Close this Arcade" %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>
        
<br>
<%= render 'games/game' %>