config/routes.rb
Rails.application.routes.draw do

  

resources :arcades do
    resources :games
  end

  resources :games, only: [:index, :show, :new, :create, :edit, :update]
  resources :players


  root 'static#home'
  get '/signup' => 'players#new'
  get '/signin' => 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/')
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcade Central</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header float-right">
          <div class"float-right">
            <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
            <a class="navbar-brand" href="<%= arcades_path %>"/>Arcades</a>
            <a class="navbar-brand" href="<%= games_path %>"/>Games</a>
            <tab>
            <a class="navbar-brand" style="padding-left: 720px;" href="<%= logout_path %>"> Log Out</a>
          </div>
        </div>
      </div>
    </div>


    <div class="container"  role="main">
      <% if flash[:notice] %>
        <div class="flash-notice">
          <% flash.each do |key, value| %>
            <div><%= value %></div>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>